language: node_js
node_js:
  - "10"
deploy:
	app: biotree-backend
  provider: heroku
  api_key:
    secure: Dt5gJxLcJ8HjwrR6BFAcrVrzEVshn5yWBwjLwgrI9GgDzG8Xip1KlX/pMyUoXROGG+U7gS+L1zWPkKDboyEM8xI8pEEVhWVnE4/sV5ydrmKzIVEEbst3lLWMx1nmzNcD7Do1vOrZMOBztvjmyY/BzWI1Gjdzkk/4bdOWK39xsgzObbDSI3qege6UKpic2uEGMTIFeHeHTHF6ouOMcdnuQziIedSjX41gzMHDh4lbsQd+WecCVTU96DbNbKnN0thS7MV2VMNT9saH8oDI6Me+99zSkd8zLwvMmsg5vAolf/KtJgylXwsIpNPtQRBCP0frO+TZixrShKHj7WE6OxYsh14IWQAKPEToVXTh1SK+MocnZp1WeX+tlKp39LNjphGvLRIYcQ2UeAw++pkGFq3EdVtZdJZWLazRzNhjNOzD4JE0qcWsOgcBPG0ou7hzJmVHoM1AzyaNXSsrc4GhHdpJ1UMbUNQyrMcKdYpzxWBvZUB3HCVhVy+soj5TV9hey69o1bb9yhO//Eem0iyX+gbXYMLV32MX09xEmk5SJ0yF9xYhszpYFKRqp4XrQx4B4xEfgcxSv8zzsNHfsqeB1VkeOnT44MR6gDgzZxqkl4hdC3ul410hW2wwX8oa8jYPqc4L7YPKozHTK4YbV3frWXfbP+wSxV3suJC7+3mXevGKfUU=
	app: biotree-test-backend  
	provider: heroku
  api_key:
    secure: bTVs9X6ay3lcNS+M+GxQ4tzSI+DZ4pPlpHEd68Yym2eoeaZvsDwFeKE5RjxMW2EU8CvaTfwB6FCPtogsB4CD6uzwq1FYET8r8yt14YH1sMmu5mQumSKsj+Y5VZ5J3/CS4uIJ/5u4/FdmES7XFmmJKAyAoEy/ZAx4egpp6dTukHWX8OYJehF7VWX1XMRaIlBV17yO9gWIypgr7OSJX3wNc1ycByyRVBIsKg/CNt0j/+64uqEgqKuxjaFpO8NRv/mGlxxnrS5iNSfM1lWYm+524ckUVDJwFWVDXW7uqK0XO8v372StRaEVkM4wlO6AchDbKt5WZuwRpxtw2DCcXJp+G0Rq/tNUCUogZypWGK5czkqQJHmbQ6uF/9o9qM1K1f9Qk06gImY/vQ/8wFIouRt6a5Fm12SSOe7fBAMYo/mJ/xU1GuiK26BftKV8gX5QWzPnUstY6/9jDJE6tJhRNCifzdWofeBL7/U1oeqtEjU124NFtKFbSxignTR6Iv+wIBGF/nPSgCgABa9q+4ktzk+pUd4FKdX4IEBj8jPt9Tbg4hau+0KDKLdzxRYF4a4okOPrWUrrTuJ5kw+MeJwkH5CaI9NyIvfi5gl3BP3ksij1PdXQaZj0gOreTO4UY20rqrkUDK9qfR03rjWFCGtFbJKim4+Tdz7MZAb+o9JjET4KPB0=
